# Generated by Django 4.0.4 on 2022-05-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=60, null=True)),
                ('hotel', models.CharField(max_length=60, null=True)),
                ('rating', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartureInfoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departureplace', models.CharField(max_length=60, null=True)),
                ('departuredate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('name', models.CharField(max_length=60, null=True)),
                ('price', models.CharField(max_length=10, null=True)),
                ('nightamount', models.CharField(max_length=2, null=True)),
                ('description', models.TextField(null=True)),
                ('additionalinformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.additionalinfomodel')),
                ('departureinformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.departureinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('surname', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=60, null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('phoneNumber', models.CharField(max_length=16, null=True)),
                ('passportNumber', models.CharField(max_length=12, null=True)),
                ('tourinformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.tourmodel')),
            ],
        ),
    ]
