# Generated by Django 4.0.4 on 2022-05-04 18:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=60)),
                ('hotel', models.CharField(max_length=60)),
                ('rating', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DepartureInfoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departureplace', models.CharField(max_length=60)),
                ('departuredate', models.DateTimeField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerAccountModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=16)),
                ('passportNumber', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='TourModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=10)),
                ('nightamount', models.CharField(max_length=2)),
                ('additionalinformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.additionalinfomodel')),
                ('departureinformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.departureinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('managerinformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.manageraccountmodel')),
                ('tourinformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.tourmodel')),
                ('userinformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.userinfomodel')),
            ],
        ),
    ]
