# Generated by Django 4.0.4 on 2022-05-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departureinfomodel',
            name='departuredate',
            field=models.DateTimeField(),
        ),
    ]
