# Generated by Django 4.0.4 on 2022-05-05 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_departureinfomodel_departuredate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmodel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='tours/images/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
