# Generated by Django 4.0.4 on 2022-05-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_alter_tourmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourmodel',
            name='image',
            field=models.ImageField(upload_to='tours/images/'),
        ),
    ]
